"""add latitude and longitude to locations

Revision ID: 64779774da5c
Revises: ef60234a372f
Create Date: 2025-11-15 22:28:17.606224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64779774da5c"
down_revision: Union[str, Sequence[str], None] = "ef60234a372f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("locations", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("locations", sa.Column("longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "longitude")
    op.drop_column("locations", "latitude")
    # ### end Alembic commands ###
